### ISSUE TITLE
Module 'swr-firestore' has no exported member 'add'.

### ISSUE THREAD

**Issue by dsernst** [nandorojo/swr-firestore#25]
Readme describes an exported function [add](https://github.com/nandorojo/swr-firestore/blob/90fc7d44cc7ceabc62f5e3c0b3e86ceaaf92c842/README.md#addpath-data):

<img src="https://user-images.githubusercontent.com/6340841/86582726-f5ba7c00-bf36-11ea-9e0f-0a2f6fb052ea.png" width="400px">

and

![image](https://user-images.githubusercontent.com/6340841/86582720-f226f500-bf36-11ea-8c33-82b696caa83d.png)

But trying to use it gives me this Typescript error:

![image](https://user-images.githubusercontent.com/6340841/86582453-7e84e800-bf36-11ea-998a-2d7410d47550.png)

Just to be safe, I tried using it anyway — in case just the type definition was missing — but this still led to a runtime error: `TypeError: undefined is not a function`.

Am I doing something wrong?

I tried updating to the latest npm version `@nandorojo/swr-firestore@0.10.0`, but no luck.

**Comment by dsernst** [comment]
The good news is

```ts
firebase.firestore().collection('mycollection').add(newDoc)
```

still works 😄

**Comment by nandorojo** [comment]
Ah, you’re right, sorry about that! I took `add` out a while back due to a hard-to-manage bug: the local cache doesn’t know which queries to add the document to. The solution for now is to either 

1. use the `add` returned by `useCollection`
2. use the firestore `.add()` function as you just did, and set the `useCollection` to `listen: true`.

Thanks for the catch, I’ll update the readme!
