### ISSUE TITLE
Add Static Mutation Does not Exist

### ISSUE THREAD

**Issue by mwood23** [nandorojo/swr-firestore#38]
Library looks super exciting, thanks for making it! Based on the [docs](https://github.com/nandorojo/swr-firestore#addpath-data) there should be an `add` static mutation exported. However, when I look in the [source it's not there](https://github.com/nandorojo/swr-firestore/blob/master/src/hooks/static-mutations.ts). What's the recommended way to add a document to a collection?

**Comment by nandorojo** [comment]
Thanks for the reminder here, duplicating from (https://github.com/nandorojo/swr-firestore/issues/25#issuecomment-654350632). I took `add` out of the library a while back, I just removed it from the docs now. You can still use it when it's hooked into a specific query returned by `useCollection`.

```js
const { add } = useCollection('users')
```

However, if you want to use add statically, for now, I would just do something like this:

```js
import { fuego, revalidateCollection } from '@nandorojo/swr-firestore'

const add = (doc) => {
  fuego.db.collection('users').add(doc)
  
  // optionally, you could add this...
  // it will refetch all queries that have the `users` collection
  revalidateCollection('users') // <- only do this if you have listen set to false, and if you are not paginating data.
}
```

**Comment by armouti** [comment]
I've been doing this by using the `set` function, `set('collection/newDocName', { ...data })`. The only thing with this is if there's a doc with the same id it would overwrite it, not sure if there's any other drawbacks.

**Comment by nandorojo** [comment]
My only hesitation to including `add` is that people might expect it to update the cache. As I'll elaborate below, it won't always do so, which could be perceived as a bug. If there's enough interest, I can include `add` and just mention this caveat in the docs.

----

>I've been doing this by using the set function, set('collection/newDocName', { ...data }). The only thing with this is if there's a doc with the same id it would overwrite it, not sure if there's any other drawbacks.

You're welcome to use the `set` workaround, as @armouti suggested. Just know that it won't always update the cache if you don't have `listen: true` on your collections.

# Why isn't `add` already included?

No matter what, adding items to a collection will never be perfect with the local cache, **unless** your queries for the collection have `listen: true`. The reason `set` works, in general, is because you're mutating a document that is potentially already in the local cache. But it doesn't have to get added to a collection via the cache. 

## Here's an example to illustrate

Let's say we have a query for the `users` collection. And then we `add` a document to it.

**1. Fetch users with team `barcelona`**

```js
const { data } = useCollection('users', { where: ['team', '==', 'barcelona'] })

// data = [{ id: 'pique', team: 'barcelona' }]
```

**2. Add a user to the collection with ID `messi`**

```js
import { add } from '@nandorojo/swr-firestore' // hypothetical add function, it doesn't exist!

add('users/messi', { team: 'barcelona' })
```

**So, what happens when I call `add` above?** 

Will this library update the cache, and add the `messi` document to the first `users` collection query? **Not necessarily.** And herein lies the problem. 

It might look like the cache will get updated by calling `add`, but it won't always do so.

This library can't know under the hood whether or not the `users/messi` document should be added to the cache for the first collection query. 

Only Firestore itself determines which documents should show up in collection queries. We can still store the `users/messi` collection in the cache, but it wouldn't update the `useCollection('users', {...})` query.

### The solution

The way to fix the example above, such that the cache updates with any collection additions, would be to set `listen: true`.

```js
useCollection('users', { where: ['name', '==', 'lionel'], listen: true })
```

**Comment by goleary** [comment]
I wanted to be able to add documents to a collection but without having to pull anything from that collection. I created this custom hook.

```
export const useAddLink = () => {
  const result = useCollection<Link>('links',{ limit: 0 });
  return { addLink: result.add };
};
```

Not sure if there are any side effects to this approach but it seems to be working for me.

**Comment by nandorojo** [comment]
The only reason I have suggested against this in the past is that it might make developers think that my library is adding this document to their collection cache. In favor of an easier DX, I can include `add` as a static mutation, and just make it clear that it won't do anything fancy to edit the cache.
