### ISSUE TITLE
What is the purpose of fuego class?

### ISSUE THREAD

**Issue by tapkain** [nandorojo/swr-firestore#69]
Hello, I'm grateful for this awesome library. Question - why do we need to pass a fuego instance? Why firebase cannot be instantiated by the user and then used by the library? And also is there a specific reason to name the class fuego, because it sounds like a library name class but actually it is more of a utility class. Thanks

**Comment by nandorojo** [comment]
Since there are multiple ways of initializing firebase, using a single class instance means this library doesn't actually know what "Firebase" is. Instead, it accesses a `fuego` variable which you give it. 

This makes it easy to change to custom firebase versions (https://github.com/nandorojo/swr-firestore/issues/59#issuecomment-719950071), use multiple firebase apps, or add a unique Firebase wrapper like react-native-firebase (https://github.com/nandorojo/swr-firestore/issues/39#issuecomment-681046958). If this lib directly imported firebase, you'd lose this control.

This library also exposes `fuego`, which you can import in your app. This way, you know you're always using the same instance that the lib is.

**Comment by nandorojo** [comment]
> Why firebase cannot be instantiated by the user and then used by the library?

If you want to do this, I suggest making a custom `Fuego` class like I did in the examples linked to in my previous comment.

**Comment by tapkain** [comment]
alright, thank you for the quick answers!
